name: bulletin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-255.0.dev
# froilan version

# version: 1.0.0+1

# environment:
#   sdk: ^3.6.0-216.1.beta
# ervon version

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

assets:
  -assets/ndmu.png
